---
title: epergaboni
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
Tale Sample: Minimal Jekyll theme for storytellers
baseurl: "/tale"
url: https://github.com/epergaboni
google_analytics: UA—XXXXXXXX-X
author:
  name: Eper Gaboni
  url: https://github.com/eperg/tale
  email: hi@epergaboni.com
markdown: kramdown
include:
- _pages
sass:
  sass_dir: _sass
  style: compressed
plugins:
- jekyll-feed
- jekyll-paginate
- jekyll-seo-tag
permalink: "/:year-:month-:day/:title"
paginate: 5
exclude:
- Gemfile
- Gemfile.lock
- tale.gemspec
disqus: jekyll-tale
